import Navbar from "@/components/layout/Navbar";
import SideBar from "@/components/layout/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanQueryProvider from "@/utils/providers/tanstackQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanQueryProvider>
        <body className={inter.className}>{children}</body>
      </TanQueryProvider>
    </html>
  );
}
